export enum DIType {
  ENTITY_CONTEXT = 'ENTITY_CONTEXT',
  REPOSITORY_FACTORY = 'REPOSITORY_FACTORY',
  DB_CONNECTION = 'DB_CONNECTION',
  AUTH_CONTROLLER = 'AUTH_CONTROLLER',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  EMAIL_MESSAGES_FACTORY = 'EMAIL_MESSAGES_FACTORY',
  USER_ROUTE = 'USER_ROUTE',
  APPLICATION = 'APPLICATION',
}
